// Code generated by sql2gorm. DO NOT EDIT.
package entity

import (
	"time"
)

type Class struct {
	ID        int       `gorm:"column:id;primary_key;AUTO_INCREMENT" json:"id"`
	Title     string    `gorm:"column:title" json:"title"`
	CreatedAt time.Time `gorm:"column:created_at" json:"created_at"`
	UpdatedAt time.Time `gorm:"column:updated_at" json:"updated_at"`
	IsDelete  int       `gorm:"column:is_delete;default:0" json:"is_delete"`
	DeletedAt time.Time `gorm:"column:deleted_at" json:"deleted_at"`
	Icon      string    `gorm:"column:icon" json:"icon"`
}

func (m *Class) TableName() string {
	return "m_class"
}

