	
// Code generated by sql2gorm. DO NOT EDIT.
package entity

import (
	"time"
)

type Item struct {
	ID          int       `gorm:"column:id;primary_key;AUTO_INCREMENT" json:"id"`
	Title       string    `gorm:"column:title" json:"title"`
	Description string    `gorm:"column:description" json:"description"`
	Url         string    `gorm:"column:url" json:"url"`
	CreatedAt   time.Time `gorm:"column:created_at" json:"created_at"`
	UpdatedAt   time.Time `gorm:"column:updated_at" json:"updated_at"`
	IsDelete    int       `gorm:"column:is_delete;default:0" json:"is_delete"`
	DeletedAt   time.Time `gorm:"column:deleted_at" json:"deleted_at"`
	ClassID     int       `gorm:"column:class_id;default:0" json:"class_id"`
}

func (m *Item) TableName() string {
	return "m_item"
}