// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"bookmark/internal/biz"
	"bookmark/internal/config"
	"bookmark/internal/data"
	"bookmark/internal/middleware"
	"bookmark/internal/pkg/log"
	"bookmark/internal/router"
	"bookmark/internal/service"
	"github.com/gin-gonic/gin"
)

// Injectors from wire.go:

func wireApp(conf *config.Configuration, opts ...gin.OptionFunc) (*App, func(), error) {
	engine := gin.Default(opts...)
	auth := middleware.NewAuth(conf)
	logger, err := log.NewLogger(conf)
	if err != nil {
		return nil, nil, err
	}
	dataData, cleanup, err := data.NewData(conf)
	if err != nil {
		return nil, nil, err
	}
	userRepo := data.NewUserRepo(dataData)
	userBiz := biz.NewUserBiz(userRepo, conf)
	userService := service.NewUserService(logger, userBiz, conf)
	routerRouter := router.NewRouter(engine, auth, userService, logger)
	app := NewApp(engine, conf, routerRouter, logger)
	return app, func() {
		cleanup()
	}, nil
}
